baseURL = 'https://npatch.github.io/'
languageCode = 'en-us'
theme = "LoveIt"
avatar = "avatar.jpg"
title = "Adventures in programming, games and more"

[module]
[[module.imports]]
  path = "loveit"

[params]
  copyright-year = '2024'
  title = "npatch's blog"
  description = "Adventures in programming, games and more"
  [params.author]
    email = 'npatsiouras@gmail.com'
    name = 'Nikolaos Patsiouras'
    postSignName = "Nikos"
  [params.layouts]
    rfc_1123 = 'Mon, 02 Jan 2006 15:04:05 MST'
    rfc_3339 = '2006-01-02T15:04:05-07:00'
  # LoveIt theme version
  version = "0.2.X"
  defaultTheme = "dark"
  [params.header]
  description = "Adventures in programming, games and more"
  [params.header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "Adventures in Programming"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    typeit = false

[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = "/images/avatar.jpg"
# title shown in home page (HTML format is supported)
title = ""
# subtitle shown in home page
subtitle = "Adventures in programming, games and more"
# whether to use typeit animation for subtitle
typeit = true
# whether to show social links
social = true
# disclaimer (HTML format is supported)
disclaimer = ""



# whether to use robots.txt
# ???? robots.txt
enableRobotsTXT = true
# whether to use git commit log
# ???? git ??
enableGitInfo = true
# whether to use emoji code
# ???? emoji ??
enableEmoji = true



[menu]

[[menu.main]]
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), uch #as icons
post = ""
name = "Posts"
url = "/posts/"
# title will be shown when you hover on this menu link
title = ""
weight = 1

#[[menu.main]]
#identifier = "tags"
#pre = ""
#post = ""
#name = "Tags"
#url = "/tags/"
#title = ""
#weight = 2

#[[menu.main]]
#identifier = "categories"
#pre = ""
#post = ""
#name = "Categories"
#url = "/categories/"
#title = ""
#weight = 3

# Markup related configuration in Hugo
[markup]

# Syntax Highlighting (https://gohugo.io/content-management/yntax-highlighting)
[markup.highlight]
# false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/#158)
noClasses = false

[taxonomies]
tag = 'tags'


# Home page posts
[params.home.posts]
enable = false
# special amount of posts in each home posts page
paginate = 6

[params.social.X-Twitter]
weight = 1
id = "@npatsiouras"
title = "X"

[params.social.Mastodon]
weight = 2
id = "@npatsiouras"
prefix = "https://mastodon.gamedev.place/web/"
title = "Mastodon"

[params.social.bluesky]
weight = 3
id = "npatsiouras.bsky.social"
title = "bluesky"

[params.social.LinkedIn]
weight = 4
id = "@npatsiouras"
title = "LinkedIn"

[params.social.Github]
weight = 5
id = "NPatch"
title = "GitHub"


# Footer config
[params.footer]
enable = true
# Custom content (HTML format is supported)
custom = ''
# whether to show Hugo and theme info
hugo = true
# whether to show copyright info
copyright = true
# whether to show the author
author = true
# site creation time
since = 2024
# ICP info only in China (HTML format is supported)
icp = ""
# license info (HTML format is supported)
#license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


[params.page.comment]
  enable = true
  # Disqus comment config
  [params.page.comment.disqus]
    # LoveIt NEW | 0.1.1
    enable = true
    # Disqus shortname to use Disqus in posts
    shortname = "Nikos P."


